///app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/utils/SessionProvider";
import Providers from "@/Providers";
import { getServerSession } from "next-auth";
import { ThemeProvider } from "@/context/ThemeContext";
import { SearchProvider } from "@/context/SearchContext";
import 'svgmap/dist/svgMap.min.css';
import { LoadingProvider } from "@/context/LoadingContext";
import { AdProvider } from "@/context/AdContext";
import Script from "next/script";
// import LoadingSpinner from "@/components/LoadingSpinner";
// import RouteChangeLoader from "@/components/RouteChangeLoader";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "3DDatabase",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-SVS4HFGW1H"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-SVS4HFGW1H');
          `}
        </Script>

        {/* Clicky */}
        <Script
          strategy="afterInteractive"
          async
          data-id="101489355"
          src="//static.getclicky.com/js"
        />

        {/* Hotjar */}
        <Script id="hotjar" strategy="afterInteractive">
          {`
            (function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:6504984,hjsv:6};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
            })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
          `}
        </Script>
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <LoadingProvider>
            <SessionProvider session={session}>
              <SearchProvider>
                <AdProvider>
                  <Providers>
                  {children}
                  </Providers>
                </AdProvider>
              </SearchProvider>
            </SessionProvider>
          </LoadingProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
